"""baseline

Revision ID: c4e0a47be900
Revises: 
Create Date: 2026-04-13 12:10:50.262569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0a47be900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game_copies')
    with op.batch_alter_table('game_copies', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('game_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_game_reservation_copy_per_booking', ['booking_id', 'game_copy_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])
        batch_op.drop_column('table_reservation_id')

    with op.batch_alter_table('game_tag_links', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_game_tag_link', ['game_id', 'game_tag_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])
        batch_op.drop_column('table_reservation_id')

    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_ts',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_ts',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('party_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('party_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_ts',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_ts',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_reservation_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'table_reservations', ['table_reservation_id'], ['id'])
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('game_tag_links', schema=None) as batch_op:
        batch_op.drop_constraint('uq_game_tag_link', type_='unique')

    with op.batch_alter_table('game_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_reservation_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'table_reservations', ['table_reservation_id'], ['id'])
        batch_op.drop_constraint('uq_game_reservation_copy_per_booking', type_='unique')
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('game_copies', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('_alembic_tmp_game_copies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('copy_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('condition_note', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('copy_code')
    )
    # ### end Alembic commands ###
